### ISSUE TITLE
Windows tests

### ISSUE THREAD

**Issue by denniskl** [ContinuumIO/odo#68]
Sorry for opening a new ticket, but I'm not sure how to reopen the old one ...

Most of the tests are passed on my Windows, Python 2.7 computer, except for:

Connection forbidden: Most probably related to a firewall on my computer ...
```
_______________________ ERROR collecting test_mongo.py ________________________
test_mongo.py:15: in <module>
←[1m    conn = pymongo.MongoClient()←[0m
..\..\..\pymongo\mongo_client.py:377: in __init__
←[1m    raise ConnectionFailure(str(e))←[0m
←[1m←[31mE   ConnectionFailure: [Errno 10061] Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte←[0m
```

Test file missing .. (I used pip install to install package to my local python installation). Test is passed when airline.sas7bdat is available in the test directory.
```
________________________ ERROR collecting test_sas.py _________________________
test_sas.py:18: in <module>
←[1m    sasfile = SAS7BDAT(test_path)←[0m
..\..\..\sas7bdat.py:422: in __init__
←[1m    self._file = open(self.path, 'rb')←[0m
←[1m←[31mE   IOError: [Errno 2] No such file or directory: 'c:\\Python27\\Lib\\site-packages\\into\\backends\\tests\\airline.
sas7bdat'←[0m
```

'ssh' is not defined in 'except socket.error:'

```
________________________ ERROR collecting test_ssh.py _________________________
test_ssh.py:25: in <module>
←[1m    ssh.close()←[0m
←[1m←[31mE   NameError: name 'ssh' is not defined←[0m
←[1m←[31m========== 137 passed, 5 skipped, 2 xfailed, 3 error in 7.10 seconds ==========←[0m
```

**Comment by mrocklin** [comment]
Thanks for reporting this, and opening a new ticket is fine.  Fortunately all of these issues are on the periphery of `into` and not particularly essential.  The mongo and ssh tests fail because your local machine doesn't have a mongo database or ssh server to test against.  The sas error is just due to our not managing test data well

None of them should stop you from using into generally.

I'll try to handle these in the next day or two.

**Comment by cpcloud** [comment]
ssh tests should probably be skipped on windows, since that isn't traditionally present on windows boxes.

**Comment by denniskl** [comment]
Well, the ssh test failed due to a minor bug and can be simply fixed with:

ssh = None
try:
    ssh = connect(hostname='localhost')
except socket.error:
    pytest.importorskip('does_not_exist')
finally:
    if not ssh is None:
        ssh.close()

**Comment by mrocklin** [comment]
I resolved this (I think) here
https://github.com/ContinuumIO/into/commit/69940bb2a8918140b8bd795708e246cf1a8c6240

**Comment by mrocklin** [comment]
I believe that these issues have now been resolved.  We skip tests appropriately and bundle the data file along with the package.  I'll leave this open for a couple of days in case I'm still missing things (or if new things have come up.)

**Comment by cpcloud** [comment]
closing as fixed. @denniskl please reopen if you're still experiencing issues.
